name: Context - Github,Env,VARS

on:
 push:
 workflow_dispatch:
env:
 MY_VAR: "Workflow"
 MY_GLOBAL_VAR: ${{vars.MY_GLOBAL_VAR}}
jobs:
 context-github:
  runs-on: ubuntu-latest
  steps:
   - name: Display Information
     run: |
      echo "Event name is ${{github.event_name}}"
      echo "Reference details is ${{github.ref}}"
      echo "SHA value is ${{github.SHA}}"
      echo "Actor value is ${{github.actor}}"
      echo "Workflow details ${{github.workflow}}"
      echo "Run id is ${{github.run_id}}"
      echo "Run number is ${{github.run_number}}"
      echo "local var value is ${{env.MY_VAR}}"
      echo "VARS value is ${{env.MY_GLOBAL_VAR}}"
      echo "VARS value is global ${{vars.MY_GLOBAL_VAR}}"
      
    
       
      
