name: Context - Github,Env

on:
 push:
 workflow_dispatch:
env:
 MY_VAR: "Workflow"
jobs:
 context-github:
  runs-on: ubuntu-latest
  env:
   MY_VAR: "Jobs"
  steps:
   - name: Display Information
     env:
      MR_VAR: "steps"
     run: |
      echo "Event name is ${{github.event_name}}"
      echo "Reference details is ${{github.ref}}"
      echo "SHA value is ${{github.SHA}}"
      echo "Actor value is ${{github.actor}}"
      echo "Workflow details ${{github.workflow}}"
      echo "Run id is ${{github.run_id}}"
      echo "Run number is ${{github.run_number}}"
      echo "local var value is ${{env.MY_VAR}}"
     
       
      
