name: Environment with Input

on:
 workflow_dispatch:
  inputs:
   TARGET_ENVIRONMENT:
    type: environment
    default: STAGING
jobs:
 env-inputs:
  runs-on: ubuntu-latest
  environment: ${{inputs.TARGET_ENVIRONMENT}}
  steps:
   - name: echo environemnt vars
     run: |
      echo "Env secret ${{secrets.API_KEY}}"
      echo "Env var ${{vars.USER_NAME}}"
