name: First Workflow

run-name: ${{github.actor}}

on:
 push:
 workflow_dispatch:
  

jobs: 
 first-job:
  runs-on: ubuntu-latest
  steps:
   - name: Step1
     run: echo 'First workflow- job1'
     
 second-job:
   runs-on: windows-latest
   steps:
    - name: Step2
      run: echo 'First workflow- job2'
