name: Action for Set up Java

on:
 workflow_dispatch:

jobs:
 echo-action:
  runs-on: ubuntu-latest
  steps:
   - name: Setup Java JDK
     uses: actions/setup-java@v4.7.0
     with:
       java-version: '17'
       distribution: 'microsoft'
       
      
     
     
   
